### ISSUE TITLE
Useful Recipes

### ISSUE THREAD

**Issue by jpt13653903** [jpt13653903/LaTeX_UCT_Report#2]
Since you've accepted the invitation, I suppose I can assign some tasks to you ;-)

You have a plethora of useful recipes for stuff like writing good abstracts / introductions / lit reviews / conclusions, etc...  Please could you add those to the report template?  I think future students will find them most useful.

The Methodology, Design and Experimentation chapters also need some work (and a bit of explanation to guide 
prospective report-writers in the correct direction).  Feel free to go wild...

I've protected the master branch, so please work in a side branch and issue a pull-request when you're done.  I'll review and merge to master.

**Comment by swinberg** [comment]
Yes, sure thing! I'd be happy to integrate those guidelines and template
aspects, and hopefully more people would be able to make use of those
things. (And might help cut down my emails by directing students to those
pages.)

**Comment by swinberg** [comment]
Is there any way to comple the Report in one go. I've been running make in
the main direction and it of course goes through making all of the
templates, to save time if would be nice to make just the report so that I
can view my changes more quickly.

Should I rather just use *LaTeX_UCT_Report\Report\Report.tex* in TexStudio
and then compile from the IDE? I was worried it might mess things up doing
so.

**Comment by jpt13653903** [comment]
Indeed -- the make all_options are for production purposes...

The easiest is to press F5 in your favourite IDE (TeXmaker, TeXstudio, VS-Code, whatever).

You could of course run "make" inside the "Report" folder as well, but that's much more tedious than "F5"

**Comment by swinberg** [comment]
In terms of the UCT Report ... is this intended more for a BSc Hons report
/ dissertation or a Lab report, I was initially thinking dissertation, so
I've probably added extraneous details which would be far more than what is
wanted for a simpler lab report (there are of course some things that are
still similar, but in that can the Methodology can be more about the
methodology used for the lab experiment etc., so the earlier version was
more appropriate).

**Comment by jpt13653903** [comment]
I've essentially followed the version on the [Wiki](http://wiki.ee.uct.ac.za/LaTeX#Templates), which has the two different title pages to cater for the two different cases (thesis vs. lab report)...  At the moment I'm using it directly for my PhD dissertation by simply defining the [title page correctly](https://github.com/jpt13653903/PhD/blob/Dissertation/LaTeX/Dissertation/Dissertation.tex#L5).

In truth, however, you wouldn't use the "report" for a lab report -- you don't need chapters.  You would use the "article" instead, typically with the `\Formalfalse` flag.  So, to answer your question: I think treating the "report" as a honours / masters / PhD report is fine.

**Comment by swinberg** [comment]
Great, thanks for the clarification, I'll continue adding things. There's a
possible issue around methodology and design chapters, I'll add some
explanations to those which you can look over and possibly discuss further.

**Comment by jpt13653903** [comment]
> I'm done with the Design chapter, and plan to press on to the Experiment and Results chapters tomorrow if I find the time (perhaps once I've got that done you could have a look over the updates).

Great :-)

You can create a pull-request when you're done and I'll review and merge it.  Thank you for all the time you're spending on it -- much more than I originally had in mind, but much appreciated.

P.S.  I included the quote above because you've added your post to the closed pull request #3, instead of posting it to the issue thread.

**Comment by swinberg** [comment]
Thanks for the tips, I'll try to put responses in the right places .
The templates etc needed refinements and this looks to be a good means to
consolidate various writing advice etc. that students of various levels can
draw upon (and hopefully lear Latex at the same time if they haven't used
it before).
